    export class CompanyBusinessPartnerUnit 
        {   
            id: any;
            businessunit_id :any;
            businessunit_code:any;
            businessunit_name:any; 
            dist_code:any;
            company_code:any;
            mailing_address:any;
            postid:any;
            country_name:any;
            state_code:any;
            state_name:any;
            city_code:any;
            city_name:any;
            pin_code:any;
            office_contactno:any;
            work_phoneno:any;
            mobile_no:any;
            email_id:any;
            website_name:any;
            company_scode:any;
            fin_period_from:any;
            fin_period_to:any;
            work_address:any;
            use_audit_feature:any;
            decimal_place:any;
            businessunit_active:any;
            maintain_warehouse:any;
            maintain_department:any;
            incometax_required:any;
            salestax_required:any;
            servicetax_required:any;
            roc_required:any;
            tds_required:any;
            maintain_licencedetails:any;
            pan_no:any;
            pan_circle_no:any;
            pan_wardno:any;
            pan_accessing_officer:any;
            inhouse_responsibleperson:any;
            outside_responsibleperson:any;
            remarks_otherinfo:any;
            circleno:any;
            taxpayment_type:any;
            taxpayment_date:any;
            returnfilling_type:any;
            returnfilling_date:any;
            gstin_no:any;
            tin_no:any;
            cst_no:any;
            sales_inhouse_responsibleperson:any;
            sales_outside_responsibleperson:any;
            sales_remarks_otherinfo:any;
            sales_circleno:any;
            sales_taxpayment_type:any;
            sales_taxpayment_date:any;
            sales_returnfilling_type:any;
            sales_returnfilling_date:any;
            servicetax_no:any;
            service_nature:any;
            service_inhouse_responsibleperson:any;
            service_outside_responsibleperson:any;
            service_remarks_otherinfo:any;
            service_circleno:any;
            service_taxpayment_type:any;
            service_taxpayment_date:any;
            service_returnfilling_type:any;
            service_returnfilling_date:any;
            roc_inhouse_responsibleperson:any;
            roc_outside_responsibleperson:any;
            roc_remarks_otherinfo:any;
            roc_circleno:any;
            roc_taxpayment_type:any;
            roc_taxpayment_date:any;
            roc_returnfilling_type:any;
            roc_returnfilling_date:any;
            otherdetails_remarks:any;
            add:any;
            company_id:any;
            fin_year:any;
            username:any;
    
            companyBusinessUnitDetails: companyBusinessUnitDetails[];
    }

    export class companyBusinessUnitDetails
    {
        sln_no:any;
        licence_no:any;
        licence_name:any;
        expiry_date:any;
        remarks:any;
        doc_name:any;
    }
        