export class transporter {
    transporter_code:any;
    transporter_name:any;
    bpgroup_code:any;
    acc_req:any;
    adv_pay_acc:any;  
    agent_com_rate:any;
    agent_fiata:any;
    agent_iata_code:any;
    agent_trans_type:any;
    ai_cal:any;
    bank_acc_no:any;
    bank_auth_code:any;
    bd_req:any;
    bpgroup_name:any;
    branchsl_no:any;
    brodetails_req:any;
    broker_code:any;  
    broker_name:any;
    bu_code:any;
    bu_name:any;
    cash_limit:any;
    costcenter_app:any;
    creadit_days:any;
    creadit_limit:any;
    cst_no:any;
    cus_party_type:any;
    dcp_indays:any;
    def_tds_nature:any;

    discount:any;
    doc_list:any;
    doc_name:any;
    dve_checkcrdays:any;
    emp_imp_type:any;
    forex_acc_no:any;
    gst_no:any;
    iec_code:any;
    iv_areafctd:any;
    mbalance_btob:any;
    pan_no:any;
    party_acc:any;
    party_nature:any;
    pay_control_acc:any;
    pay_term:any;
    prov_bank_dtls:any;
   
    sdetails_req:any;
    stax_regno:any;
    tan_no:any;
    tds_req:any;
    tin_no:any;
    tran_type:any;
    trans_active:any;
    trans_alt_name:any;
    trans_blk_allow:any;
    trans_blk_reason:any;
    trans_currency:any;
    transbill_add1:any;
    transbill_add2:any;
    transbill_add3:any;
    transbill_city:any;
    transbill_country:any;

    transbill_name:any;
    transbill_pin:any;
    transbill_state:any;
    transdelv_add1:any;
    transdelv_add2:any;
    transdelv_add3:any;
    transdelv_city:any;
    transdelv_country:any;
    transdelv_name:any;
    transdelv_pin:any;
    transdelv_state:any;
   
   //Dynamic Address Details
        cperson_name:any;
        cperson_desig:any;
        cperson_phone:any;
        cperson_mobile:any;
        cperson_email:any;
        cperson_website:any;
        cperson_addr1:any;
        cperson_addr2:any;
        cperson_addr3:any;
        cperson_country:any;
        cperson_state:any;
        cperson_city:any;
        cperson_pin:any;
        cp_bill_addr:any;
  

}
